export const LESSON_BY_USER_ID_REQUEST = 'LESSONS_BY_USER_ID_REQUEST'
export const LESSON_BY_USER_ID_SUCCESS = 'LESSON_BY_USER_ID_SUCCESS'
export const LESSON_BY_USER_ID_FAIL = 'LESSON_BY_USER_ID_FAIL'

export const LESSONS_CREATE_REQUEST = 'LESSONS_CREATE_REQUEST'
export const LESSONS_CREATE_SUCCESS = 'LESSONS_CREATE_SUCCESS'
export const LESSONS_CREATE_FAIL = 'LESSONS_CREATE_FAIL'

export const LESSONS_FIND_BY_LESSON_ID_REQUEST = 'LESSONS_FIND_BY_LESSON_ID_REQUEST'
export const LESSONS_FIND_BY_LESSON_ID_SUCCESS = 'LESSONS_FIND_BY_LESSON_ID_SUCCESS'
export const LESSONS_FIND_BY_LESSON_ID_FAIL = 'LESSONS_FIND_BY_LESSON_ID_FAIL'

export const FLAT_LESSON_TRY = 'FLAT_LESSON_TRY'
export const FLAT_LESSON_ADD = 'FLAT_LESSON_ADD'
export const FLAT_LESSON_FAIL = 'FLAT_LESSON_FAIL'
